'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, Mail, ShieldCheck, Users } from 'lucide-react';
import StatCard from '@/components/AdminUser/StatCard';
import DonutChart, { DonutLegendRow, type DonutSlice } from '@/components/shared/DonutChart';

type AdminMetrics = {
  success_rate: number;
  total_emails: number;
  active_alerts: number;
  total_users: number;
  user_roles?: Record<string, number>;
};

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://127.0.0.1:5000';

function formatNumber(value: number) {
  return Number.isFinite(value) ? value.toLocaleString() : '0';
}

const ROLE_COLORS: Record<string, string> = {
  admin: 'var(--c-chart-1)',
  super_user: 'var(--c-chart-2)',
  superuser: 'var(--c-chart-2)',
  sales_user: 'var(--c-chart-4)',
  salesuser: 'var(--c-chart-4)',
  operation_user: 'var(--c-chart-3)',
  operationuser: 'var(--c-chart-3)',
  staff: 'var(--c-chart-6)',
  user: 'var(--c-chart-6)',
  unknown: 'var(--c-chart-6)',
};

function formatRoleLabel(role: string) {
  const labels: Record<string, string> = {
    admin: 'Admin',
    super_user: 'Super',
    superuser: 'Super',
    sales_user: 'Sales',
    salesuser: 'Sales',
    operation_user: 'Operation',
    operationuser: 'Operation',
    staff: 'Staff',
    user: 'User',
    unknown: 'Unknown',
  };

  return labels[role] ?? role.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function buildUserRoleSlices(roles: Record<string, number> = {}): DonutSlice[] {
  return Object.entries(roles)
    .filter(([, value]) => value > 0)
    .map(([role, value]) => ({
      label: formatRoleLabel(role),
      value,
      color: ROLE_COLORS[role] ?? 'var(--c-chart-6)',
    }));
}

export default function AdminOverviewMetricCards() {
  const [metrics, setMetrics] = useState<AdminMetrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadMetrics() {
      try {
        setError(null);
        const response = await fetch(`${API}/api/dashboard/admin/metrics`, {
          cache: 'no-store',
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);

        const result = await response.json();
        setMetrics(result.data ?? null);
      } catch (err) {
        console.error('Failed to load admin dashboard metrics:', err);
        setError('Could not load dashboard metrics');
      } finally {
        setLoading(false);
      }
    }

    loadMetrics();
  }, []);

  const cards = [
    {
      title: 'Milestone Success Rate',
      value: loading ? '...' : `${metrics?.success_rate ?? 0}%`,
      hint: error ?? 'Completed milestones percentage',
      tag: 'Live',
      icon: <ShieldCheck size={18} color="var(--c-success)" />,
    },
    {
      title: 'Total Generated Emails',
      value: loading ? '...' : formatNumber(metrics?.total_emails ?? 0),
      hint: 'Emails generated by the system',
      tag: 'Total',
      icon: <Mail size={18} color="var(--c-accent)" />,
    },
    {
      title: 'Active Alerts',
      value: loading ? '...' : formatNumber(metrics?.active_alerts ?? 0),
      hint: 'Alerts currently requiring attention',
      tag: 'Active',
      icon: <AlertTriangle size={18} color="var(--c-danger)" />,
    },
  ];

  const userRoleSlices = buildUserRoleSlices(metrics?.user_roles);
  const totalUsers = metrics?.total_users ?? 0;

  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
        gap: 12,
        marginBottom: 20,
      }}
    >
      {cards.map((card) => (
        <StatCard
          key={card.title}
          title={card.title}
          value={card.value}
          hint={card.hint}
          tag={card.tag}
          icon={card.icon}
        />
      ))}

      <div className="stat-card">
        <div className="stat-card__top">
          <div className="stat-card__left">
            <div className="stat-card__iconWrap">
              <Users size={18} color="var(--c-chart-2)" />
            </div>
            <div className="stat-card__title">Total Users</div>
          </div>
          <div className="stat-card__tag">Users</div>
        </div>

        {loading ? (
          <>
            <div className="stat-card__value">...</div>
            <div className="stat-card__hint">Loading user distribution</div>
          </>
        ) : (
          <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginTop: 12 }}>
            <DonutChart
              slices={userRoleSlices}
              size={72}
              thickness={7}
              centerValue={formatNumber(totalUsers)}
              centerLabel="users"
            />
            <div style={{ flex: 1, minWidth: 0 }}>
              {userRoleSlices.length > 0 ? (
                userRoleSlices.map((slice) => (
                  <DonutLegendRow
                    key={slice.label}
                    color={slice.color}
                    label={slice.label}
                    value={slice.value}
                  />
                ))
              ) : (
                <div className="stat-card__hint">No users found</div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
