-- =============================================================================
-- SAS — super user digest email log
-- One row per super-digest email actually attempted (sent or failed), so the
-- admin panel can show which automatic emails went out. Run once in the
-- Supabase SQL editor.
-- =============================================================================

CREATE TABLE IF NOT EXISTS super_digest_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  super_email text NOT NULL,
  department  text NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('overdue', 'reminder')),
  item_count  integer NOT NULL DEFAULT 0,
  subject     text,
  status      text NOT NULL CHECK (status IN ('sent', 'failed')),
  error       text,
  sent_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS super_digest_log_sent_at_idx    ON super_digest_log (sent_at DESC);
CREATE INDEX IF NOT EXISTS super_digest_log_super_email_idx ON super_digest_log (super_email);

-- RLS — the backend writes/reads this with the anon key, so it needs explicit
-- policies (same pattern as sales_digest_log.sql / operations_digest_log.sql).
-- Re-runnable.
ALTER TABLE super_digest_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS allow_select_super_digest_log ON super_digest_log;
CREATE POLICY allow_select_super_digest_log ON super_digest_log
  FOR SELECT USING (true);

DROP POLICY IF EXISTS allow_insert_super_digest_log ON super_digest_log;
CREATE POLICY allow_insert_super_digest_log ON super_digest_log
  FOR INSERT WITH CHECK (true);
